# Generated by Django 4.1.9 on 2023-11-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclebalance',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
