# Generated by Django 4.1.9 on 2023-11-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_materialstorecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialstorecycle',
            name='mesure_unity',
            field=models.CharField(max_length=50, unique=False),
        ),
        migrations.AlterField(
            model_name='materialstorecycle',
            name='name',
            field=models.CharField(max_length=150, unique=False),
        ),
        migrations.AlterField(
            model_name='materialstorecycle',
            name='price',
            field=models.FloatField(unique=False),
        ),
    ]
