# Generated by Django 4.1.9 on 2023-11-15 00:21

import core.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('total', models.FloatField()),
                ('operation_type', models.IntegerField()),
                ('balance_ids', djongo.models.fields.ArrayField(model_container=core.models.RecycleBalanceOccurrence)),
            ],
        ),
        migrations.RemoveField(
            model_name='recyclebalance',
            name='mesure_unit',
        ),
        migrations.AddField(
            model_name='recyclebalance',
            name='mesure',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='materialstorecycle',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
