# Generated by Django 4.1.9 on 2023-11-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operationsbalance_remove_recyclebalance_mesure_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recyclebalance',
            old_name='user_id',
            new_name='user_id_occurrence',
        ),
        migrations.AlterField(
            model_name='materialstorecycle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
