# Generated by Django 4.1.9 on 2023-11-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_id_recyclebalance_user_id_occurrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
                ('current_total', models.FloatField()),
                ('total_earned', models.FloatField()),
                ('last_operation', models.DateTimeField()),
            ],
        ),
    ]
